import open3d as o3d
import numpy as np
import re
import os
import argparse
import sys

# --- Configuration ---
# Map your class names to RGB colors (0-1 range)
CLASS_COLORS = {
    "wall": [0.5, 0.5, 0.5],       # Grey
    "pipe": [1.0, 0.0, 0.0],       # Red
    "valve": [0.0, 1.0, 0.0],      # Green
    "boiler": [0.0, 0.0, 1.0],     # Blue
    "electric_equipment": [1.0, 1.0, 0.0], # Yellow
    "hose": [1.0, 0.0, 1.0],       # Magenta
    "default": [0.0, 1.0, 1.0]     # Cyan (Unknown)
}

def parse_layout_file(file_path):
    """
    Parses the ground truth layout .txt file generated by the BlenderProc script.
    Returns a list of dictionaries containing bbox parameters.
    """
    boxes = []
    
    with open(file_path, 'r') as f:
        lines = f.readlines()
        
    for line in lines:
        line = line.strip()
        if not line: continue
        
        # Regex to parse 'key=Type(params)'
        # Examples:
        # bbox_0=Bbox(pipe,1.0,2.0,0.5,0.0,0.5,0.5,1.0)
        # wall_0=Wall(ax,ay,z_bot,bx,by,z_bot,height,thickness)
        
        match = re.match(r"(.*)=(.*)\((.*)\)", line)
        if not match: continue
        
        obj_type = match.group(2) # "Bbox" or "Wall"
        params = match.group(3).split(',')
        
        if obj_type == "Bbox":
            # format: class_name, cx, cy, cz, angle_z, dim_x, dim_y, dim_z
            cls_name = params[0]
            vals = [float(x) for x in params[1:]]
            
            box_data = {
                "class": cls_name,
                "center": np.array([vals[0], vals[1], vals[2]]),
                "angle": vals[3],
                "extent": np.array([vals[4], vals[5], vals[6]]),
                "type": "bbox"
            }
            boxes.append(box_data)
            
        elif obj_type == "Wall":
            # format: ax, ay, z_bottom_a, bx, by, z_bottom_b, height, thickness
            vals = [float(x) for x in params]
            ax, ay, z_base = vals[0], vals[1], vals[2]
            bx, by = vals[3], vals[4]
            height, thickness = vals[6], vals[7]
            
            # Convert Wall start/end representation to Center/Extent/Rotation
            dx = bx - ax
            dy = by - ay
            length = np.sqrt(dx**2 + dy**2)
            angle = np.arctan2(dy, dx)
            
            cx = (ax + bx) / 2.0
            cy = (ay + by) / 2.0
            cz = z_base + (height / 2.0)
            
            box_data = {
                "class": "wall",
                "center": np.array([cx, cy, cz]),
                "angle": angle,
                "extent": np.array([length, thickness, height]),
                "type": "wall"
            }
            boxes.append(box_data)
            
    return boxes

def create_o3d_bounding_box(box_data):
    """
    Creates an Open3D OrientedBoundingBox from parsed data.
    """
    # 1. Rotation Matrix (Rotation around Z axis)
    angle = box_data["angle"]
    R = np.array([
        [np.cos(angle), -np.sin(angle), 0],
        [np.sin(angle),  np.cos(angle), 0],
        [0,              0,             1]
    ])
    
    # 2. Create Box
    bbox = o3d.geometry.OrientedBoundingBox(box_data["center"], R, box_data["extent"])
    
    # 3. Color
    cls = box_data["class"]
    color = CLASS_COLORS.get(cls, CLASS_COLORS["default"])
    bbox.color = color
    
    return bbox

def main(room_id, base_path):
    # Updated paths for flat directory structure (directly in Downloads)
    pcd_path = os.path.join(base_path, f"room_{room_id:04d}.ply")
    layout_path = os.path.join(base_path, f"room_{room_id:04d}.txt")
    
    print(f"Looking for files in: {base_path}")
    
    if not os.path.exists(pcd_path):
        print(f"Error: Point cloud file not found: {pcd_path}")
        return
    if not os.path.exists(layout_path):
        print(f"Error: Layout file not found: {layout_path}")
        return

    print(f"Loading Room {room_id}...")
    
    # --- 1. Load Point Cloud ---
    pcd = o3d.io.read_point_cloud(pcd_path)
    if pcd.is_empty():
        print("Warning: Point cloud is empty.")
    else:
        print(f"Loaded {len(pcd.points)} points.")

    min_bound = pcd.get_min_bound()
    max_bound = pcd.get_max_bound()
    room_size = max_bound - min_bound
    print(f"Room Bounds: Min {min_bound}, Max {max_bound}")
    print(f"Total Dimensions (LxWxH): {room_size[0]:.2f}m x {room_size[1]:.2f}m x {room_size[2]:.2f}m")

    if np.any(min_bound < -0.01) or np.any(max_bound > 32.01):
        print("!!! WARNING: Room exceeds SpatialLM bounds (0-32m) !!!")
    # --- 2. Load and Create Bounding Boxes ---
    layout_data = parse_layout_file(layout_path)
    geometries = [pcd]
    
    print(f"Loaded {len(layout_data)} bounding boxes.")
    
    for item in layout_data:
        obb = create_o3d_bounding_box(item)
        geometries.append(obb)

    # --- 3. Visualize ---
    # Add a coordinate frame (Red=X, Green=Y, Blue=Z)
    coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1.0, origin=[0, 0, 0])
    geometries.append(coord_frame)
    
    print("Opening visualizer...")
    o3d.visualization.draw_geometries(geometries, window_name=f"Room {room_id}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Visualize Point Cloud and Bounding Boxes")
    # Using '0802' as the example default based on your prompt
    parser.add_argument("--id", type=int, default='0000', help="Room ID (e.g. 802)")
    parser.add_argument("--path", type=str, default="/Users/jo/Downloads/", help="Folder containing .ply and .txt files")
    
    args = parser.parse_args()
    
    main(args.id, args.path)